com:
  bancodebogota:
    ptdo:
      rest:
        endpoint:
          wsparametro: http://10.84.32.154:8084/parametro/%s
      parametro:
        endpointBUSPreAprobados: endpointProductCampPotentialSaleInquiry
        canal: canal
        terminalId: terminalId
        bankId: bankId
server:
  port: 8086
